authorName: unik
experimentName: example_mnist
trialConcurrency: 4
maxExecDuration: 10h
maxTrialNum: 10
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
trial:
  #command: CUDA_VISIBLE_DEVICES=0 python main.py
  command: python main.py
  codeDir: .
  gpuNum: 1
localConfig:
  useActiveGpu: true
  maxTrialNumPerGpu: 1
  gpuIndices: "0"

