#data_list: ['MPQA', 'SST2', 'Subj', 'TREC', 'MR', 'CustomReview']
data_path: ./data/SST2
res_path: ./data/preprocessed 
# 两个保证有一个有embedding文件就好
embedding_path: ['../../../opt/embeddings/GoogleNews-vectors-negative300.txt',
                 '../data/embeddings/GoogleNews-vectors-negative300.txt']
seed: 42
valid_rate: 0.2
best_model_path: data/save
cuda_index: 0
output_channels: 100
max_length: 100
batch_size: 50
epoch_size: 256
lr: 0.0005
patience: 10
l2: 1e-5
max_grad_norm: 3.0
esp: 1e-5
kfold: 10
dropout: 0.5
filters: [3, 4, 5]

# train_mode: ['random', 'static', 'fine-tuned']
use_pretrained: False
train_mode: 'random'
emb_dim: 300